

clean:
	find . -type f | grep "\./." | grep -v Makefile | grep -v svn | xargs rm -rf

#	find . -type f | grep "\./." | grep -v Makefile | grep -v svn
#	(cd i386-linux/; $(MAKE) clean)
#	(cd ppc-darwin/; $(MAKE) clean)
