#!/bin/bash

## This script downloads a pre-compiled binary for those that don't
## have access to the Chez Scheme compiler.

which svn > /dev/null
svn info | grep Revision | sed s/Revision:\ // > svn_rev.txt

if [ "" == "$1" ];
then REV=`cat svn_rev.txt`;
else REV="$1";
fi

MT=`./depends/get_machine_type`

SOFILE=$REV"_"$MT"_main_chez.so"
WSPARSEFILE=$REV"_"$MT"_wsparse"

echo Downloading precompiled binary for Regiment revision $REV
#echo Fetching file from: "http://www.regiment.us/regiment_binaries/"$REV"_"$MT"_main_chez.so"
echo
echo If this doesn\'t work there might not be a precompiled binary for this SVN revision.
echo Check what revisions have binaries available at: 
echo   http://www.regiment.us/regiment_binaries/
echo

if [ `which wget` ];
then wget  "http://www.regiment.us/regiment_binaries/"$MT"/"$SOFILE;
     wget  "http://www.regiment.us/regiment_binaries/"$MT"/"$WSPARSEFILE;
elif [ `which curl` ];
then curl "http://www.regiment.us/regiment_binaries/"$MT"/"$SOFILE -o $SOFILE;
     curl  "http://www.regiment.us/regiment_binaries/"$MT"/"$WSPARSEFILE -o $WSPARSEFILE;
else echo NEITHER CURL NOR WGET AVAILABLE!!; exit 1
fi 

echo Moving to build/$MT/main_chez.so
mv $SOFILE build/$MT/main_chez.so
echo Moving to bin/wsparse
mv $WSPARSEFILE bin/wsparse
chmod +x bin/wsparse
