#!/bin/bash

## This is a very simple script to get you up and running quickly.
## Run it from the directory in which it resides.

export REGIMENTD=`pwd`
export PATH=$REGIMENTD/bin:$PATH
export PATH=$PATH:$REGIMENTD/depends
