#!/bin/bash


if (which links > /dev/null) ;
then WEB='links -no-numbering -no-references -dump'
elif (which elinks > /dev/null);
then WEB='elinks -no-numbering -no-references -dump'
elif (which lynx > /dev/null) ;
then WEB='lynx -dump'
else echo error: Please install 'lynx', 'links', or 'elinks'!; exit -1
fi

$WEB http://regiment.us/regression | grep passed | tail 

echo
echo Above are the revisions that pass full system tests.
echo Please install the most recent of these.
