#!/bin/bash

source /usr/bin/assert_regimentd

# This is a nasty hack.
#find /usr/lib/wavescript/ -name "*.sls.ikarus-fasl"  | xargs touch 
find $REGIMENTD/ -name "*.sls.ikarus-fasl"  | xargs touch 

# Build the parser on the client side.
echo "Building parser using this machine's mzscheme."
(cd "$REGIMENTD/src/parser/" && mzc --auto-dir -z *.ss)
