#!/bin/bash

source /usr/bin/assert_wavescriptd

# This is a nasty hack.
#find /usr/lib/wavescript/ -name "*.sls.ikarus-fasl"  | xargs touch 
find $WAVESCRIPTD/ -name "*.sls.ikarus-fasl"  | xargs touch 

# Build the parser on the client side.
echo "=============================================="
echo "Building parser using this machine's mzscheme."
echo "=============================================="
(cd "$WAVESCRIPTD/src/parser/" && mzc --auto-dir -z *.ss)
