.TH WSC2 1

.SH NAME
wsc2 \- The WaveScript Compiler, C backend ver 2

.SH SYNOPSIS
.B wsc2
.I source-file.ws
[
.BI \-O \ level
]
.SH DESCRIPTION

The
.BR wsc2 (1)
command compiles a complete WaveScript program into ANSI C code.


.SH OPTIONS


.SH ENVIRONMENT VARIABLES

.SH SEE ALSO
.BR ws (1),
.BR ws.early (1),
.BR wsmlton (1),
.BR wstiny (1),
.BR wsjava (1)
.br
 The WaveScript user's manual - 
.I http://regiment.us/man
