#!/bin/sh

# Normally 1-10 by 1-6


NOISE=6

# for i in `seq 0 10 40`;
#   do
#     # FIRST RUN
#     echo test -f "./logs/prog1/deadsimple_thresh"$i"_noise"$NOISE".log.gz" ; 
#     if test -f "./logs/prog1/deadsimple_thresh"$i"_noise"$NOISE".log.gz" ; 
#     then echo "Log already exists! Noise:"$NOISE" and Thresh:"$i; 
#     else 
# 	echo "P1: RUNNING IT -- Noise:"$NOISE" and Thresh:"$i;
# 	../run_querysim.ss -param $i -noise $NOISE \
# 	    -f "../prog1.rs" \
# 	    -l "./logs/prog1/deadsimple_thresh"$i"_noise"$j".log.gz" \
# 	    -w "../world.simworld";
#     fi 
#     # THEN ANALYZE CONCURRENTLY:
# #	(../analyze_vs_groundtruth.ss \
# #	    -l "./logs/deadsimple_thresh"$i"_noise"$j".log.gz" \
# #	    -o ./data/results_thresh"$i"_noise"$j".dat &)
#   done 


for i in `seq 0 10 40`; do 
    echo test -f "./logs/prog2/deadsimple_thresh"$i"_noise"$NOISE".log.gz" ; 
    if test -f "./logs/prog2/deadsimple_thresh"$i"_noise"$NOISE".log.gz" ; 
    then echo "Log already exists! Noise:"$NOISE" and Thresh:"$i; 
    else 
	echo "P2: RUNNING IT -- Noise:"$NOISE" and Thresh:"$i;
	../run_querysim.ss -param $i -noise $NOISE \
	    -f "../prog2_manual.tm"  \
	    -l "../logs/prog2/deadsimple_thresh"$i"_noise"$NOISE".log.gz"  \
	    -w "../world.simworld"; 
    fi; 
done

# ../run_querysim.ss -param 0 -noise $NOISE \
#     -f "../prog0.rs"  \
#     -l "../logs/prog0.log.gz"  \
#     -w "../world.simworld"; 
