#!/bin/bash

# Examples:
#   run quick runall
#   run full run0 

export NOISE=6

# First build world.simworld if it's not there.

# Process first argument.
if [ "$1" == "quick" ]; 
then 
	export NUMNODES=30
	export BASENAME=smallrun_
	export LOWER=0
	export STEP=10
	export UPPER=40
elif [ "$1" == "full" ]; 
then 
	export NUMNODES=200
	export BASENAME=fullrun_
	export LOWER=0
	export STEP=5
	export UPPER=40
else 
    echo First arg to run must be \"quick\" or \"full\"!
    exit -1
fi

function do_run() {
    echo Doing a sequence of runs.  
    echo Params: ln:$LOGFILENAME infile:$INPUTFILE low:$LOWER step:$STEP hi:$UPPER noise:$NOISE
    for i in `seq $LOWER $STEP $UPPER`; do 
	echo test -f "./logs/""$LOGFILENAME"_thresh$i"_noise"$NOISE".log.gz" ; 
	if test -f "./logs/""$LOGFILENAME"_thresh$i"_noise"$NOISE".log.gz" ; 
	    then echo "Log already exists! Noise:"$NOISE" and Thresh:"$i; 
	else 
	    echo "RUNNING $INPUTFILE -- Noise:"$NOISE" and Thresh:"$i;
	    ./run_querysim.ss -param $i -noise $NOISE \
		-f "./$INPUTFILE"  \
		-l "./logs/""$LOGFILENAME"_thresh$i"_noise"$NOISE".log.gz" \
		-w "./world.simworld"; 
	fi; 
    done
}


function run0() {
    export LOGFILENAME=prog0/$(BASENAME)
    export INPUTFILE=prog0.rs
    do_run; 
}
#    (cd ./paper_figures; nice -n 10 ./runall)


# Now dispatch on the rest of the arguments.

run0;

