#!/bin/bash

base=`$REGIMENTD/depends/get_machine_type --threaded`

# if [ "$base" == ""  ]      || 
#    [ "$base" == "ppcosx" ] || 
#    [ "$base" == "i3nt" ]   ;
# then
#   echo "ERROR: machine type $base does not have threaded version."
#   exit -1
# fi

#echo "t"$base
echo $base
