#!/bin/bash

# This is redundant with depends/get_machine_type but returns the
# threaded version.  An alternative would be to return the result of
# "get_machine_type" and add a "t".



# This gets the machine type in the format used by Chez Scheme.
# It echoes that machine type to stdout.

#MT=`echo '(display (machine-type))' | $REGIMENTD/depends/petite -q`

# It's a little tricky to do using uname...
MACHINE=`uname -s -m`
if   [ "$MACHINE" == "Linux i686" ];             then MT=ti3le;
elif [ "$MACHINE" == "Linux i586" ];             then MT=ti3le;
elif [ "$MACHINE" == "Linux x86_64" ];           then MT=ta6le;
#elif [ "$MACHINE" == "Darwin Power Macintosh" ]; then MT=ppcosx;
elif [ "$MACHINE" == "Darwin i386" ];            then MT=ti3osx;
#elif [ "$MACHINE" == "Darwin i386" ];            then MT=ta6osx;

#elif [ "$MACHINE" == "CYGWIN_NT-5.1 i686" ];     then MT=i3nt;
else echo Unknown platform for scheme system: $MACHINE;
     exit -1;
fi

echo $MT
