#!/bin/sh

# [2005.11.19] It's lame that I had to put this in a separate file,
# but I still don't know how to effectively use pipes WITHIN a command
# executed by xargs.

#sed 's/#;/`/' $1 > $2 

#sed 's/#;/`/g' $1 | sed 's/#|//g' | sed 's/|#//g' | sed -e 's/\[/\(/g' | sed -e 's/\]/\)/g' > $2 
#sed $1 -e 's/#;/`/g' -e 's/#|//g' -e 's/|#//g' -e 's/\[/\(/g' -e 's/\]/\)/g' > $2 

sed 's/#;/`/g' $1 | sed 's/#|.*|#//g' | sed -e 's/\[/\(/g' | sed -e 's/\]/\)/g' > $2 
