#!/bin/bash

# This is only relevent if you have the full version of Chez Scheme.

VER=7.3

# MACHINE=`uname`
# if [ $MACHINE == "Linux" ];
# then DIR=i3le;
#      SCHEME=scheme;
# elif [ $MACHINE == "Darwin" ];
# then DIR=ppcosx;
#      SCHEME=scheme;
# elif [ $MACHINE == "CYGWIN_NT-5.1" ];
# then DIR=i3nt;
#      SCHEME=petite.exe;
# else echo Unknown platform: $MACHINE
# fi

DIR=`$REGIMENTD/depends/get_machine_type`
SCHEME=scheme
if [ "$DIR" == "i3nt" ]; then SCHEME=petite.exe; fi

($REGIMENTD/depends/petite_chez_scheme$VER/bin/$DIR/$SCHEME -b $REGIMENTD/depends/petite_chez_scheme$VER/boot/$DIR/petite.boot -b $REGIMENTD/depends/petite_chez_scheme$VER/boot/$DIR/scheme.boot $*)
