#!/bin/bash

# This finds runs the version of Chez Scheme found based on the $CHEZD
# environment variable.

# There are two ways to call the threaded version.  Either with the
# --threaded argument or by setting the CHEZTHREADED environment
# variable to be non empty.


# ARGS=
# RELEVANT=`getopt -a -l "threaded" -o ":" -- "$@"`
# echo "SET TO $RELEVANT"
# eval set -- "$RELEVANT"
# while [ $# != 0 ];  do 
#  flag=$1
#  case $flag in 
#    "--threaded" )
#           MT=`$REGIMENTD/depends/get_machine_type --threaded`;
# 	  echo "GETTING THREADED $MT";
# 		    ;;
#    "--" ) shift; 
#           ARGS="$ARGS $*";
#           break;;
#    *)     ARGS="$ARGS $flag";;
#  esac;
#  shift;
# done


ARGS=" $* "
if [[ "$ARGS" =~ " --threaded " ]] || 
   [ "$CHEZTHREADED" != "" ]; 
then
     ARGS=${ARGS/--threaded/}
     MT=`$REGIMENTD/depends/get_machine_type --threaded`     
else 
     MT=`$REGIMENTD/depends/get_machine_type`     
fi

if [ -e "$CHEZD" ]; then
  if [ -e $CHEZD/boot/$MT/scheme.boot ];
  then FULLBOOT="-b $CHEZD/boot/$MT/scheme.boot"
  else FULLBOOT=
  fi 
  $CHEZD/bin/$MT/scheme -b $CHEZD/boot/$MT/petite.boot $FULLBOOT  $ARGS
else
 echo "env var CHEZD was not set to an existing directory!"
 exit -1
fi
