#!/bin/bash

# This gets the machine type in the format used by Chez Scheme.
# It echoes that machine type to stdout.

#MT=`echo '(display (machine-type))' | $REGIMENTD/depends/petite -q`

# It's a little tricky to do using uname...
MACHINE=`uname -s -m`
if   [ "$MACHINE" == "Linux i686" ];             then MT=i3le;
elif [ "$MACHINE" == "Darwin Power Macintosh" ]; then MT=ppcosx;
elif [ "$MACHINE" == "Darwin i386" ];            then MT=i3osx;
#elif [ $MACHINE == "Windows" ];       then MT=i3nt;
else echo Unknown platform for scheme system: $MACHINE
fi

echo $MT
