#!/bin/bash

# I use this when I make a fresh checkout on a machine that doesn't
# have a system-wide install of the Chez Scheme compiler.

# Linux only.




scp nms3.csail.mit.edu:~newton/csv7.3-i3le.tar.gz .

echo '#!/bin/bash'         > chez
echo                      >> chez
echo '$REGIMENTD/depends/csv7.3/bin/i3le/scheme -b $REGIMENTD/depends/csv7.3/boot/i3le/petite.boot -b $REGIMENTD/depends/csv7.3/boot/i3le/scheme.boot $*' >> chez
chmod +x chez

tar xzvf csv7.3-i3le.tar.gz
