#!/bin/bash

MACHINE=`uname`
VER=7.3

if [ "$MACHINE" == "Linux" ];
then DIR=i3le;
elif [ "$MACHINE" == "Darwin" ];
then DIR=ppcosx;
elif [ "$MACHINE" == "Windows" ];
then DIR=i3nt;
else echo rawscheme script: Unknown platform: "$MACHINE"
fi

$REGIMENTD/depends/petite_chez_scheme$VER/bin/$DIR/scheme $*
