#!/bin/bash

VER=7.3

# MACHINE=`uname`
# if [ "$MACHINE" == "Linux" ];
# then DIR=i3le;
# elif [ "$MACHINE" == "Darwin" ];
# #then DIR=ppcosx;
# then DIR=i3osx;
# elif [ "$MACHINE" == "Windows" ];
# then DIR=i3nt;
# else echo rawscheme script: Unknown platform: "$MACHINE"
# fi

DIR=`$WAVESCRIPTD/depends/get_machine_type`

$WAVESCRIPTD/depends/petite_chez_scheme$VER/bin/$DIR/scheme $*
