#!/bin/sh

MACHINE=`uname`

if [ $MACHINE == "Linux" ];
then DIR=i3le;
elif [ $MACHINE == "Darwin" ];
then DIR=ppcosx;
elif [ $MACHINE == "Windows" ];
then DIR=i3nt;
else echo Unknown platform: $MACHINE
fi

#$REGIMENTD/depends/petite_chez_scheme7.0/bin/$DIR/scheme $*

$REGIMENTD/depends/petite_chez_scheme7.0a/bin/$DIR/scheme $*
