#!/bin/bash

FILE=$1

# A little hackery to accept either "foo" or "foo.hs" as input:
if [ -e $FILE".hs" ]; 
then 
 BIN=$FILE
 FILE=$FILE".hs"
else
 BIN=`echo $1 | sed 's/\.hs//'`
fi

#FLAGS="$FLAGS -O2 "

#TIME=/usr/bin/time
#TIME=
#TIME=time

if [ "$GHC" == "" ];  then 
 GHC=ghc
 #GHC=ghc-6.10.4.20090726
 #GHC=ghc-6.11.20090726  
fi

#rm -f $BIN *.hi *.o
#touch $FILE

shift

if   [ "$CNC_VARIANT" == "pure" ]; then 
 echo "Using CNC_VARIANT='pure'"
 FLAGS="$FLAGS -DCNC_VARIANT=1"
elif [ "$CNC_VARIANT" == "io" ] || [ "$CNC_VARIANT" == "normal" ] ; then
 echo "Using CNC_VARIANT='normal'"
 FLAGS="$FLAGS -DCNC_VARIANT=2"
elif [ "$CNC_VARIANT" == "" ]; then
 echo " *** "
 echo " *** \$CNC_VARIANT unset (should be 'pure' or 'io'/'normal')!"
 echo " ***   Defaulting to 'pure'..."
 echo " *** "
 CNC_VARIANT="pure"
 FLAGS="$FLAGS -DCNC_VARIANT=1" 
fi

if [ "$CNC_SCHEDULER" == "" ];
then 
   if [ "$CNC_VARIANT" == "pure" ]; then
     FLAGS=" $FLAGS -DCNC_SCHEDULER=2"
     echo " *** WARNING - defaulting CNC_SCHEDULER to '2' (pure)"
   else
     FLAGS=" $FLAGS -DCNC_SCHEDULER=5"
     echo " *** WARNING - defaulting CNC_SCHEDULER to '5' (io)"
   fi
else FLAGS=" $FLAGS -DCNC_SCHEDULER=$CNC_SCHEDULER"
fi

echo "  [Compiling $FILE to $BIN]"
echo $GHC $FLAGS -cpp  --make $FILE -fforce-recomp
if $GHC $FLAGS -cpp --make $FILE -fforce-recomp
#if ghc  -cpp -O2 $FILE -o 
then 
if [ "$NORUN" == "" ]; then
  echo "  [Executing]"
  #exec $TIME ./$BIN $* 
#  $TIME ./$BIN $* 
  time ./$BIN $* 
#  exec time memprof ./$BIN $* 
fi
else exit -1
fi

