#!/bin/sh

MACHINE=`uname`

if [ $MACHINE == "Linux" ];
then DIR=i3le;
elif [ $MACHINE == "Darwin" ];
then DIR=ppcosx;
elif [ $MACHINE == "Windows" ];
then DIR=i3nt;
else echo Unknown platform: $MACHINE
fi

export SWL_ROOT=$REGIMENTD/depends/swl0.9z/swllib
export SWL_LIBRARY=$REGIMENTD/depends/swl0.9z/bin/$DIR

#echo $SWL_ROOT
#echo $SWL_LIBRARY
exec $REGIMENTD/depends/petite -b $SWL_LIBRARY/swl.boot $*
