
bc:
	(cd ../; export PLTCOLLECTS=`pwd`:$(PLTLIB); mzc --collection-zos ./plt)

nc:
	(cd ../; export PLTCOLLECTS=`pwd`:$(PLTLIB); mzc --collection-extension ./plt)

clean:
	rm -f compiled/*.zo _SIM_*

#	rm -rf compiled/native/*
