#!/bin/sh

if [ -e 6sec_marmot_sample.raw ];
then echo "Already present!"
     exit 0
fi

# URL=http://www.regiment.us/marmotdata/6sec_marmot_sample.raw
URL=http://cs.indiana.edu/~rrnewton/datasets/marmotdata/6sec_marmot_sample.raw

if [ `which wget` ];
then wget $URL
elif [ `which curl` ];
then curl "$URL" -o 6sec_marmot_sample.raw
else echo "NEITHER CURL NOR WGET AVAILABLE!!  Cannot download."; exit 1
fi 
