#!/bin/bash

COMP=.__wscMessages.txt
RUN=.__runquery_output.txt

echo > $COMP
echo > $RUN

function go () {
    if ! wsc $1 -exit-error; then exit 1; fi
    echo >> $RUN
    echo $1 : >> $RUN
#    ./run_query | head -20 >> $RUN
    if ! ./run_query >> $RUN;
    then exit 1; fi
}

# wsc demo0_audio.ws 
# echo >> $RUN
# echo DEMO0: >> $RUN
# ./run_query | head -20 >> $RUN


# echo >> $RUN
# echo DEMO1: >> $RUN
# ./run_query | head -20 >> $RUN

#go "demo0_audio.ws"
go "demo1_audiofile.ws"
# 1b, 1c

go "demo2a_iterate.ws"
go "demo2b_iterateState.ws"
go "demo3a_tuples.ws"
go "demo3b_inlining.ws"
go "demo3c_lists.ws"
go "demo3d_tuples_of_tuples.ws"

#TEMP# go "demo3e_hashtables.ws"

go "demo3f_morelists.ws"

# Disabled waiting for binary dataFile reading.
#TEMP# go "demo4_fft.ws"

go "demo5a_rewindow.ws"
go "demo5b_rewindow_inlined.ws"

go "demo6a_unionList.ws"
#go "demo6b_sync.ws"
#go "demo6c_syncN.ws"

# ;    "demo5b_better.ws"
#     "demo6_sync.ws"
#     "demo7_syncN.ws"
#     "demo8_marmot_noinline.ws"
#     "demo9_marmot.ws"
