#!/bin/bash

COMP=.__wscMessages.txt
RUN=runquery_caml_output.txt

echo > $COMP
echo > $RUN

function go () {
    echo 
    echo "testall_caml: Running $1"
    echo "============================================================"
    if ! wscaml $1 -exit-error; then exit 1; fi
    echo >> $RUN
    echo $1 : >> $RUN
    echo "================================================================================" >> $RUN
    if ! ./query.caml.exe | head -n 200 >> $RUN; then exit 1; fi
    echo
    echo Finished running query.
}

##go "demo1b_dataFile.ws"
go "demo1c_timer.ws"
##go "demo1d_dataFile_binary.ws"
##go "demo1d_readFile_text.ws"
go "demo1e_readFile.ws"

go "demo2a_iterate.ws"
go "demo2b_iterateState.ws"

go "demo3a_tuples.ws"
go "demo3c_lists.ws"
go "demo3d_tuples_of_tuples.ws"
## #TEMP# go "demo3e_hashtables.ws"
go "demo3f_morelists.ws" 
go "demo3g_arrays.ws"
##go "demo3h_advancedlists.ws"

## [2007.07.27] Can't do these anymore because we don't implement Int64:
##go "demo3i_conversion_prims.ws"
##go "demo3j_numbers.ws"
# 3k

# [2008.08.01] need clock and int64:
#go "demo4a_fft.ws"
go "demo4d_quoted_constants.ws"
go "demo4e_fifo_adt.ws"

#go "demo5a_rewindow.ws"         # int64
#go "demo5b_rewindow_inlined.ws" # int64

go "demo6a_unionList.ws"
#go "demo6b_sync.ws"             # int64
#go "demo6c_syncN.ws"            # int64 
## 6e

#go "demo7a_marmot_noinline.ws"  # int64
#go "demo7b_marmot_phase1.ws"    # int64

go "demo8a_generic_arith.ws" 
go "demo8b_sugars.ws"
go "demo8c_moresugar.ws"

# [2008.08.01] scanf problem:
# #go "demo9_misc_prim_tests.ws" # not working yet
# go "demo9b_higher_order_prims.ws"
# #gcc -c bar.c
# #go "demo9c_foreign.ws"

# #go "demo10a_simple_merge.ws"
# #go "demo10b_repeated_rewindow.ws"
# #go "demo10c_fft_ifft.ws"
