#!/bin/bash

COMP=.__wscMessages.txt
RUN=runquery_mlton_output.txt
STATUS=0

echo > $COMP
echo > $RUN

function go () {
    echo 
    echo "testall_mlton: Running $1"
    echo "============================================================"
    echo wsmlton $1 -exit-error
    if ! wsmlton $1 ; then echo "WSMLTON FAILED with $?"; exit 1; fi
    echo >> $RUN
    echo $1 : >> $RUN
    echo "================================================================================" >> $RUN
    if ! ./query.mlton.exe -n 20 > $RUN ; 
    then echo QUERY EXITED WITH ERROR STATUS;
         exit 1; 
    fi
    echo
    echo Finished running query.
}

#go "demo1b_dataFile.ws"  # Can't do text yet.
go "demo1c_timer.ws"
go "demo1d_dataFile_binary.ws"
go "demo1e_readFile.ws"

go "demo2a_iterate.ws"
go "demo2b_iterateState.ws"

go "demo3a_tuples.ws"
go "demo3c_lists.ws"
go "demo3d_tuples_of_tuples.ws"
# #TEMP# go "demo3e_hashtables.ws"
go "demo3f_morelists.ws" 
go "demo3g_arrays.ws"
go "demo3h_advancedlists.ws"   
go "demo3i_conversion_prims.ws" 
go "demo3j_numbers.ws"
# 3k
go "demo3m_sigsegs.ws"

go "demo4a_fft.ws"
go "demo4c_quoted_constants.ws"
go "demo4d_fifo_adt.ws"

go "demo5a_rewindow.ws"
go "demo5b_rewindow_inlined.ws"

go "demo6a_unionList.ws"
go "demo6b_sync.ws"
go "demo6c_syncN.ws"
go "demo6e_stdlib_sync.ws"

go "demo7a_marmot_noinline.ws"
go "demo7b_marmot_phase1.ws"

go "demo8a_generic_arith.ws" 
go "demo8b_sugars.ws"
go "demo8c_moresugar.ws"

# go "demo9_misc_prim_tests.ws" # not working yet
go "demo9b_higher_order_prims.ws" 
#gcc -c bar.c
go "demo9c_foreign.ws"
#go "demo9d_foreign_pointer.ws"
go "demo9f_foreign_source.ws"

go "demo10a_simple_merge.ws"
go "demo10b_repeated_rewindow.ws"
go "demo10c_fft_ifft.ws"
