
#COMPONENT = TokenMachineRuntime
COMPONENT = TestMachine
#COMPONENT = BasicTMComm

## RRN: Added this according to instructions found online to get rid
## of the "calls ... are uncombined" warning.
#PFLAGS += -DDELUGE_GENERIC_COMM_PROMISCUOUS
# Didn't work!!

include Makerules



